### ISSUE TITLE
Feature: Use a human-friendly id for each URL

### ISSUE THREAD

**Issue by Cerchie** [Contenda-Team/share-pear#6]
In the [blog post](https://dev.to/contenda/using-netlify-on-demand-builders-astro-edge-functions-to-make-a-blog-sharing-generator-20lf) that explains the architecture behind this tool, Cassidy says that _"Right now we use a [UUID](https://www.npmjs.com/package/uuid4) for each URL, but we might change that up later on to something more human-language friendly."_ 

There's a way to do it with base 62 outlined in [this StackOverflow post](https://stackoverflow.com/questions/9543715/generating-human-readable-usable-short-but-unique-ids). 

It's a .net question, but I'm including it because it points out that you'd need to dedupe these ids and store them somewhere. 

Here's a way to do it in [node.js](https://stackoverflow.com/questions/30468292/how-to-generate-base62-uuids-in-node-js). 

Now, there's a [library out there](https://hashids.org/) that helps take care of a couple concerns that would arise if this was a roll-your-own solution:

1. hashids looks out for swears
2. a salt is added to enforce uniqueness, so no deduping is needed directly

Might also want to compare hashids to [nanoid](https://github.com/ai/nanoid) for size. 

Another alternative: could do it in a more involved way ala [Instagram](https://instagram-engineering.com/sharding-ids-at-instagram-1cf5a71e5a5c), but there's no backend here, so there'd be a need to hook up PostgreSQL etc for their solution or the other solutions listed. 

The hashids site helpfully [lists a few more alternatives](https://hashids.org/#are-there-any-alternatives). 

My last question is: how would these ids be stored? Would it be on the deployment servers, so would there even be a need to store them?

**Comment by Cerchie** [comment]
Ah this is on the Share Pear side-- closing.

**Comment by cassidoo** [comment]
Thanks Lucia for the messages anyway! We actually ended up doing the base 62 way on the platform, so, awesome call. ❤️
